language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install

notifications:
  slack:
    secure: QQ19DUDcWoKK19B2OlGSprrYsc5OfSFyAwnSNgn5iyS2kSswpz8mkVEYvg+sKzGSabmF7h6NmFqdTtmqttZug0opl+UelX+ZQz3deuYGCaYXKXKb+8dpPAfFpQwkDXxFUpUiCcT4sQfhgLh75NLyTmcT8r7aWtSfqgKbBn1yjgC9xQVK2814TcRVJjIRgXj1usfINw6PVEUPUdOQQqoP8+15Zo4ZJ4is+TKenCablT0IY2+WIQFIiwi0JdAPb0AXpdzqcMiE2TYjgTURXJuaBLAiQG7D/vm7iq+QN1N6421eJK7zrwuA2oBYza1T7idelWJECQFga9WJShrfPNjTR80+V8P6tPSZENZ51E+dMSvNHXhs81YISArdI+U5pFeuImmmpxtsgAhTbbdXhBJGnpthlPxe+Ot7dHM1+Lvb2NKgZj2q1e/SfV92eeFpO18/dxZjeVVryX6JQpezHBkM0/WWRVT/nncFagpm3VzQ0Oj/dFW81r0s2JIK+tXWf1CzOA1BI2aFfZCwA83vxNG+ESvaIpA14ZFNNdTW2YoT8S/G0U/QmB0LmnoLxZ+I/cUXkjNEIq/wcw87S9hgk7JWNbalCw1uLauZAPIZLy1yzCbx6AIFC8/Hb1yP9ppxK+vASlU4xHbCievT2YABL5Uu2KNxuRqT4p4A9ez+W/ZIKtg=
